// ...existing code...
class GLWidget : public QOpenGLWidget, protected QOpenGLFunctions
{
    // ...existing code...
public slots:
    void deleteSelectedObjects();  // Add new slot
    // ...existing code...
private:
    bool isCrossingSelection;     // Add new member
    // ...existing code...
};
